### PR TITLE
 Added tables for speakers and attendance sections.

### PR DESCRIPTION
**Pull request by OpesanyaAdebayo**

### CODE REVIEW

**Review by inidaname — COMMENTED** [review]
Nice approach but should we have a theme for this and if I may suggest also have a document guide on how to submit topic proposal something to go with CFP

**Comment by OpesanyaAdebayo** [comment]
Thank you @inidaname.
The theme is Node NG Conf 2018.
We haven't yet announced CFP. I'll work on the document guide as soon as we do so in less than 2 weeks.

**Review by codeekage — APPROVED** [review]
LGTM

**Comment by codeekage** [comment]
@inidaname could you design one on this repo. So, we could land this and proceed?

**Comment by inidaname** [comment]
@Codeekage We can work with the UI @chukundah shared on slack, the page should have such links for  easy to refer.

**Review by inidaname — COMMENTED** [review]
Is it okay to indicate that ticket is free. Or that there will be a proposed price to announce.

**Comment by codeekage** [comment]
@inidaname add the CFP and guide for speakers to the README.md file on this repo.

**Comment by inidaname** [comment]
@Codeekage I just learned about the existence of this proposal I am not the right person to set this up, mine was just a suggestion a way for me to know what we actually intend to achieve here.

More reason why I press on having a meeting before creating such proposals but enlighten me more and I will see what I can do.

**Comment by OpesanyaAdebayo** [comment]
I would actually be in the best place to work on the doc. I'll try to put something together as soon as I can. Please pardon me for the slight delays. There are a lot of moving parts to putting the conference together.

I'm thinking of making a Google form for people to submit talks, for now. I don't know how long it'll take for the website to be ready, and we have to announce CFP in less than 2 weeks from now.

@inidaname Yes, I don't think there should be a problem indicating that it's a free conference. Thanks for pointing that out.

**Comment by inidaname** [comment]
Even with the website in place Google Form is the better option

**Comment by inidaname** [comment]
@OpesanyaAdebayo I will send a draft on the guide, you can edit to suite the event, I noticed you mention that you may have so much on you.

**Comment by OpesanyaAdebayo** [comment]
Thank you @inidaname. That would be greatly appreciated. 🙏

**Review by inidaname — APPROVED** [review]

**Comment by codeekage** [comment]
Whoever updating the docs should also consider taking drafting what it takes to host or organize events... leave getting SWAGs for an event to me. Thank you!

**Comment by chukundah** [comment]
The page I designed was for Node Africa.

Once the information for the conference is intact, I'll design one for NG.

Meanwhile I'll get one of my front-end engineers to implement the current design and we should get it up by the end of the day.

**Comment by codeekage** [comment]
@chukundah please approve this PR

**Pull request merged**
